### ISSUE TITLE
Update Question Titles to conform to best practice length

### ISSUE THREAD

**Issue by debjudy** [18F/cv_faq#1007]
Best practice for title length (H1) is 20-70 characters. 43% of current questions have lengths greater than 70 characters.  Revise longer titles to align with best practice.

## Definition of Done
- [ ] Approved and merged from content administrator
- [ ] Merged to production by engineer
- [ ] Notified agency content lead that content is published

**Comment by brandocalrissian** [comment]
other things to consider: an abbreviated title other than what's displayed to the user

**Comment by brandocalrissian** [comment]
Problem: what the users are seeing in search engine results are truncated questions (after ~70 characters). The important content for the user may not appear in the google search results and keeps the user from being able to identify the relevance of the question within the search results.

question must remain clear on the web site.

**Comment by brandocalrissian** [comment]
Research effort complete, what to do next is TBD

**Comment by brandocalrissian** [comment]
We have the knowledge. Must decide if we're doing this (informed by other ticket for tech research).
