### ISSUE TITLE
Update content governance and related documents

### ISSUE THREAD

**Issue by jonadecker** [18F/cv_faq#1013]
As a member of the TTS CV-19 Content Team, I need to ensure that documentation reflects current practices and is in a state of readiness for new team members rolling onto project.

**Comment by debjudy** [comment]
Updated content governance https://docs.google.com/document/d/1eQWMAmqIbkC8_dZz2uZjuNBGU1KN3HbjD9mgAYgmO6U/edit?usp=sharing
