### ISSUE TITLE
Review analytics for re-categorization, adapt to what we learn

### ISSUE THREAD

**Issue by brandocalrissian** [18F/cv_faq#1091]
Recategorization was deployed on Sept 25. Look at the data and determine how usage has been affected.

**Comment by brandocalrissian** [comment]
Get at least a week's worth of data.

**Comment by debjudy** [comment]
Deck of analysis https://docs.google.com/presentation/d/1mic4G4B7_Jtq3CE3TThqKoobj2xmI2tuGhdNpyXU4rc/edit#slide=id.p1
