### ISSUE TITLE
SPIKE: Link Checking

### ISSUE THREAD

**Issue by debjudy** [18F/cv_faq#1124]
Research link checking tool for use in maintaining/pruning external links cited in Best Bets

**Comment by jonadecker** [comment]
[Shortlist with features](https://docs.google.com/document/d/1dHncc-h2Ax2RwZ5cu_dPybbcEVxnc3fiuLKy8d_fjV0/edit?usp=sharing)

**Comment by brandocalrissian** [comment]
Now comes the doing part.
