### ISSUE TITLE
describe/advocate for plain language work

### ISSUE THREAD

**Issue by brandocalrissian** [18F/cv_faq#1260]
describe what we could do for HHS WRT plain language + accessibility

CDC-speak: <click here for dense tech stuff>
Plain speak (for the people!): ah i got that thank you plain language!

**Comment by debjudy** [comment]
shared deck with Tom https://docs.google.com/presentation/d/1YItTKGml4ur6boBTMaTFaPvlziJj4DOGJrYj76-HVp0/edit#slide=id.gaf517aa33b_0_0
