### ISSUE TITLE
Set up Hubspot

### ISSUE THREAD

**Issue by allisonnorman** [18F/cv_faq#306]
We are moving forward with Hubspot to aid in the content management workflow. We can use this issue to track progress:

- [ ] [Submit purchase request](https://docs.google.com/document/d/1JrKuWquI33se2rxarpdvGOow-ECAt78LTXEULSZbXPY/edit#) - @thomhalla 
- [ ] Set up account - @afeld 
- [ ] Confirm access to account  - @vbitzer @Mtcarp 
- [ ] Configure account and update workflow documentation - @abbeykos @Mtcarp @brentryanjohnson @vbitzer

**Comment by debjudy** [comment]
P-card purchase of hubspot blocked.  Re-evaluating content management approach.  Will open new issue should determination that HubSpot is desired.
