### ISSUE TITLE
Consider adding back in USWDS banner

### ISSUE THREAD

**Issue by allisonnorman** [18F/cv_faq#313]
1. Add back in "This is a government website banner"
2. Suggestion by @davemcorwin who was following along a discussion in #uswds - we should consider changing the https verbiage in the USWDS banner to:

> The https:// ensures that any information you provide is encrypted and transmitted securely.

Why did this come up? https://krebsonsecurity.com/2020/03/us-government-sites-give-bad-security-advice/
 
https://gsa-tts.slack.com/archives/C050HRGN7/p1585170289011300

**Comment by brandocalrissian** [comment]
We do not believe this will happen. If it does, it'll come back and we can open a new ticket.
