### ISSUE TITLE
Allow content to be syndicated.

### ISSUE THREAD

**Issue by thomhalla** [18F/cv_faq#404]
Create a mechanism to make our content available for syndication.

**Comment by adunkman** [comment]
Would love clarification here @thomhalla — would a JSON endpoint, like the ones implemented in #505 achieve the goal? 

Unsure if the important part of this issue is `RSS` or `content available for syndication`.

**Comment by adunkman** [comment]
Updating the ticket from clarification on https://github.com/18F/cv_faq/pull/505#issuecomment-614120334:

> yes @adunkman, json endpoint with docs achieves the goal!
