### ISSUE TITLE
Document process for resolving security vulnerabilities

### ISSUE THREAD

**Issue by allisonnorman** [18F/cv_faq#473]
We need to document how we determine whether a GH security vulnerability notice needs to be resolved and the process for resolving as we prep for vendor transition.

### We'll know we're done when:
- [ ] We have documented the process of evaluating and determining whether it's time to resolve a potential vulnerability ("Is it time to resolve this yet?" "Does this need to be resolved?")
- [ ] We have documented a template for the steps to take when resolving

Note: there are a couple we need to determine whether or not to resolve in #464 if it helps to use those to form a template.

**Comment by adunkman** [comment]
Related: https://github.com/18F/tts-tech-portfolio/issues/17
