### ISSUE TITLE
Request updated community events content from CDC

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/cv_faq#509]
- [When does the CDC recommend that I cancel or postpone an event?](https://faq.coronavirus.gov/community-events/when-does-the-cdc-recommend-i-cancel-or-postpone-events/)

- [Source content is also outdated](https://www.cdc.gov/coronavirus/2019-ncov/community/large-events/event-planners-and-attendees-faq.html#accordion-5e8c9f5642614-card-0).

**Comment by vbitzer** [comment]
Is this flagged on Airtable, and should we do it here too and open an issue @brentryanjohnson ?
