### ISSUE TITLE
FDA - 45 FAQs

### ISSUE THREAD

**Issue by vbitzer** [18F/cv_faq#513]
https://drive.google.com/drive/u/0/folders/1II_wuyCEyrCKXGPPEsXgd1r3bSF4-IsM

@brentryanjohnson if the content came from our HHS contact, how are you tagging that on labels?

**Comment by brentryanjohnson** [comment]
Good question, @vbitzer. I added a new FDA label, but now I think that might be the wrong approach. I suppose we should try to capture both "content owner" and "workflow source." We've been using the labels for workflow source, so I'll change it.

Thank you!

**Comment by thebestsophist** [comment]
- [x] added to airtable
- [ ] audit for timeliness etc.
- [ ] flag cross-agency overlaps

**Comment by vbitzer** [comment]
@thebestsophist is this checklist done? Thanks! Also @brentryanjohnson when you changed it, did you change it to "new"?

**Comment by Mtcarp** [comment]
Status update: Questions that did not require approval from agency partner were merged and published to the website. Awaiting approval from agency partner about removal of duplicate questions.

**Comment by thebestsophist** [comment]
done!

**Comment by brentryanjohnson** [comment]
This one is labeled `new`, `content origin: CDC`, `content owner: FDA`
