### ISSUE TITLE
Resolve ambiguous FAQ

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/cv_faq#514]
This question may cause confusion. It seems to be addressing home testing, but it implies there are no tests for COVID-19. Thoughts @vbitzer or @abbeykos?

**Q: Is there a test for COVID-19?**

A: Currently there is no FDA-approved or cleared test to diagnose or detect COVID-19 because the virus that causes COVID-19 is new. Therefore, the FDA has issued several Emergency Use Authorizations (EUAs) for the use of new diagnostic tests to detect the SARS-CoV-2 virus, which causes COVID-19. During public health emergencies declared under section 564 of the FD&C Act, the FDA is able to issue EUAs when certain criteria are met that allows for the use and distribution of potentially life-saving medical products to diagnose, treat, or prevent the disease, which can include diagnostic tests.

**Comment by brentryanjohnson** [comment]
This question probably addresses the issue:

**Q: Are there any tests that I can purchase to test myself at home for COVID-19?**

A: At this time, the FDA has not authorized any test that is available to purchase for testing yourself at home for COVID-19. The FDA sees the public health value in expanding the availability of COVID-19 testing through safe and accurate tests that may include home collection, and we are actively working with test developers on this goal. You can find [listings of tests](https://www.fda.gov/medical-devices/emergency-situations-medical-devices/faqs-diagnostic-testing-sars-cov-2#offeringtests) that have received an Emergency Use Authorization (EUA) as well as labs and manufacturers that have notified FDA as set forth in the FDA\'s [Policy for Diagnostic Tests for Coronavirus Disease-2019](https://www.fda.gov/regulatory-information/search-fda-guidance-documents/policy-diagnostic-tests-coronavirus-disease-2019-during-public-health-emergency).

**Comment by vbitzer** [comment]
@brentryanjohnson  agree, let's bring this up on our call today as a good example @abbeykos
