### ISSUE TITLE
Add 2 new FDA FAQs, identified by custom tracker

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/cv_faq#533]
**Q: May health care providers prescribe chloroquine phosphate or hydroxychloroquine sulfate off-label to treat patients with COVID-19?**
A: As mentioned above, chloroquine phosphate is only approved for the treatment of malaria, and hydroxychloroquine sulfate is only approved for the treatment of malaria, lupus, and rheumatoid arthritis. Once FDA has approved a drug, healthcare providers generally may prescribe or administer the drug for an unapproved use, including in clinical settings not described in the approved labeling. This decision will be based on their assessment of the potential benefits versus the risks for their patient, recognizing that FDA has not assessed the safety or effectiveness of such use.

**Q: What are the most important things I need to know to keep myself and others safe when I go to the grocery store during the pandemic?**
A: There are steps you can take to help protect yourself, grocery store workers and other shoppers, such as wearing a face covering, practicing social distancing, and using wipes on the handles of the shopping cart or basket. Read more tips in [Shopping for Food During the COVID-19 Pandemic - Information for Consumers](https://www.fda.gov/food/food-safety-during-emergencies/shopping-food-during-covid-19-pandemic-information-consumers).

**Comment by Mtcarp** [comment]
FYI @vbitzer as noted in the commit, the other question (What are the most important things I need to know to keep myself and others safe when I go to the grocery store during the pandemic) was committed directly to dev: https://github.com/18F/cv_faq/commit/e3d43b4ff9e140358edf191e7abf213eadff7eed
