### ISSUE TITLE
Duplicate CDC questions with different answers

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/cv_faq#534]
We have a problem with a CDC duplicate. The question is duplicated, but the answers are different.

One FAQ is in `protect-yourself`; the other is in `underlying-conditions`.

![Find answers about coronavirus, search term who is at higher risk shows duplicate who is at higher risk for serious illness from covid-19](https://user-images.githubusercontent.com/32855580/79783220-2ce49e00-82f5-11ea-95ec-284b99670fcd.png)

**Comment by vbitzer** [comment]
👀 @brentryanjohnson
