### ISSUE TITLE
Add new FDA FAQ

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/cv_faq#565]
Q: Is there a shortage of personal protective equipment (PPE) such as gloves, masks, and N95 respirators or of ventilators?

**Comment by Mtcarp** [comment]
@brentryanjohnson Did we alert Misty about this one? Since it wasn't submitted by her, let's hold off until she approves. 
cc: @abbeykos @vbitzer

**Comment by debjudy** [comment]
Re-opened so that we could close with comment. This question is no longer being sought to be added to FAQ.
