### ISSUE TITLE
Duplicate question in Travel category 

### ISSUE THREAD

**Issue by jonadecker** [18F/cv_faq#567]
"I'm an American citizen and I recently returned..." with related display issue (second instance always expanded)

**Comment by jonadecker** [comment]
![Second instance of question always expanded](https://user-images.githubusercontent.com/1735772/80047044-fca62680-84d1-11ea-833d-7d9589ed5916.png)

**Comment by brentryanjohnson** [comment]
Nice catch, @jonadecker! I'll take care of this in a branch I'm working on. 👍
