### ISSUE TITLE
Add and edit Animals category (2 new, 1 edit)

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/cv_faq#575]
## Animals
Content changes tracked by site tracker and found in CDC FAQ website: https://www.cdc.gov/coronavirus/2019-ncov/faq.html#COVID-19-and-Animals

### Add
- Can wild animals spread the virus that causes COVID-19 to people or pets?
- Can bats in the United States get the virus that causes COVID-19, and can they spread it back to people?

### Edit
- Since tigers can get infected with the virus that causes COVID-19, should I worry about my pet cat?
  - Changed to: Should I worry about my pet cat?

**Comment by Mtcarp** [comment]
Published and agency content lead updated.
