### ISSUE TITLE
Link participating agencies into the footer

### ISSUE THREAD

**Issue by allisonnorman** [18F/cv_faq#585]
## Description 
We need to add the new participating agencies in the footer. The list of current agencies participating can be found here: https://faq.coronavirus.gov/agency/

We are working with:
- Coronavirus.gov - Coronavirus.gov
- WhiteHouse.gov - WhiteHouse.gov 
- CDC - cdc.gov
- FEMA - fema.gov
- HHS - hhs.gov
- **DHS - dhs.gov***
- **FDA - fda.gov***
- **Treasury - treasury.gov***
- **IRS - irs.gov***
- **SBA - sba.gov***
- **USDA - usda.gov*** (Added 4/27)
- **VA - va.gov*** (Added 4/27)

***Not on footer today**, needs to be added

## We'll need to: 
- [ ] Add bolded agencies to footer and use the order specified. We should space the footer columns per the [Figma design](https://www.figma.com/file/Qm6suNoOYjYNIY3LWdneEI/FAQ.coronavirus.gov-%E2%80%94-Production-File-%5BExternal-Share%5D?node-id=0%3A1) 
- [ ] Per Tom, let's only deploy to demo branch to show the stakeholders along with the  before deploying to master
- [ ] CONTENT: Add a task of adding subsequent agencies as they onboard to the footer in the content workflow documentation

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Code is properly styled per USWDS
- [ ] Finished design has been compared against mockup
- [ ] Documentation is complete
- [ ] CircleCI tests have passed
- [ ] Automated accessibility scans have passed
- [ ] Manual accessibility testing completed
- [ ] Code has been successfully built and deployed into a staging (dev) environment

**Comment by vbitzer** [comment]
USDA and VA too

**Comment by brentryanjohnson** [comment]
I think this looks good, but I wonder if we should consider automating this. Theoretically, we could add logic to grab all the agencies in the `_agencies` directory and output the results in the footer (would also require adding agency `url` to the front matter of each agency's markdown file).

**Comment by allisonnorman** [comment]
Good call, @brentryanjohnson! I created a separate issue (#604) in the backlog for automation to consider in the future. I think for now, given the design work and new work stream, I think the intention is to get these changes on there sooner but agree this is the right way to go.

**Comment by allisonnorman** [comment]
Removed 1.2 label as @thomhalla said we can propose this change once the design changes are deployed.

**Comment by brandocalrissian** [comment]
Would need design.

**Comment by brandocalrissian** [comment]
Old, may never happen. if it does, it'll come back. closing.
