### ISSUE TITLE
Automate participating agency representation in footer

### ISSUE THREAD

**Issue by allisonnorman** [18F/cv_faq#604]
From #585: 

> We should consider automating [adding agencies to the footer once their content is on the site]. Theoretically, we could add logic to grab all the agencies in the _agencies directory and output the results in the footer (would also require adding agency url to the front matter of each agency's markdown file).

**Comment by debjudy** [comment]
Closing item since we have not addressed and because footer links have been stable for some time.  WIll open new issue should need arise.
