### ISSUE TITLE
Add return to Coronavirus.gov button

### ISSUE THREAD

**Issue by allisonnorman** [18F/cv_faq#615]
## Description
As most users are visiting from coronavirus.gov, we want to add some context for them to return back to the parent experience. We have a revised design that includes a button that links back to coronavirus.gov. 

## Notes
- This button is now visually represented on the Figma ([link](https://www.figma.com/file/Qm6suNoOYjYNIY3LWdneEI/FAQ.coronavirus.gov-%E2%80%94-Production-File-External-Share?node-id=15%3A317)). 
- It is present on the homepage header and also on the global (non-homepage) header (Figma [link](https://www.figma.com/file/Qm6suNoOYjYNIY3LWdneEI/FAQ.coronavirus.gov-%E2%80%94-Production-File-External-Share?node-id=409%3A4152)). 
- The button should point to https://coronavirus.gov

## Acceptance criteria
- [ ] Button is added on homepage header for mobile and desktop that links to coronavirus.gov
- [ ] Button is added on global header for mobile and desktop that links to coronavirus.gov

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Code is properly styled per USWDS
- [ ] Finished design has been compared against mockup
- [ ] Documentation is complete
- [ ] CircleCI tests have passed
- [ ] Automated accessibility scans have passed
- [ ] Manual accessibility testing completed
- [ ] Code has been successfully built and deployed into a staging (dev) environment

**Comment by jonadecker** [comment]
Implemented by @danielnaab per design but rolled back at Tom's request pending design revisions.

**Comment by brandocalrissian** [comment]
Would need design.

**Comment by brandocalrissian** [comment]
Old, may never happen. if it does, it'll come back. closing.
