### ISSUE TITLE
Decomission OpsGenie

### ISSUE THREAD

**Issue by allisonnorman** [18F/cv_faq#634]
We have decided as a team to decommission Opsgenie now that we no longer need to support 24/7 content changes.

Update @kfoley-18F  from 5/1/20: 

> I have had a thread with Brandon Kirby about OpsGenie and will work with Aidan to shut it down.

**Comment by allisonnorman** [comment]
Update from Kelsey: "I requested yesterday with Aidan and tech portfolio to cancel the subscription. I don’t think it’s happened yet though."

**Comment by debjudy** [comment]
Per Tom this task completed.
