### ISSUE TITLE
Update FDA species-specific coronavirus question in animals category

### ISSUE THREAD

**Issue by jonadecker** [18F/cv_faq#655]
## Description
Update FDA species-specific coronavirus question in animals category
[Preview link](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/fda-animals-update-2020-05-07/animals/if-my-pet-had-species-specific-coronavirus-are-they-more-likely-to-get-covid-19/)
 
## Definition of Done
- [x] Approved and merged from content administrator
- [ ] Merged to production by engineer
- [ ] Notified agency content lead that content is published

**Comment by vbitzer** [comment]
@jonadecker looks good @janeopm fya
