### ISSUE TITLE
Review Slack channel usage

### ISSUE THREAD

**Issue by debjudy** [18F/cv_faq#728]
For COVID-19, we have 4 TTS slack channels.  With changes to team members, we need to review usage and clarify for team.

**Comment by debjudy** [comment]
Created proposal.  Brandon reviewing what can be done with Github before making any other changes.

**Comment by brandocalrissian** [comment]
[GitHub API Reference](https://developer.github.com/webhooks/event-payloads/) detailing event data that can be sent to slack

**Comment by brandocalrissian** [comment]
Waiting on team feedback on the PR slack notification changes
