### ISSUE TITLE
Conflicting/competing search results on results page

### ISSUE THREAD

**Issue by jonadecker** [18F/cv_faq#729]
## Description

We're seeing duplicate search results on the results page, some of which appear to be "snapshots in time" and reflect old category names and old page display/styling (see search results page for `Vaccine` for example.

## Definition of Done
- [ ] Approved and merged from content administrator
- [ ] Merged to production by engineer
- [ ] Notified agency content lead that content is published

**Comment by danielnaab** [comment]
Federalist has some kind of S3-fallback for missing pages. There's nothing exposed to allow us to flush that bucket, but I'll contact Federalist folks for suggestions.

If we could get it flushed on deploy, we could potentially put search results for the terms in the old URL on the 404 template.
