### ISSUE TITLE
Research/do Slack integration to cut github notification noise

### ISSUE THREAD

**Issue by brandocalrissian** [18F/cv_faq#742]
## Description
- _What is the problem we're trying to solve?_
Slack is too noisy from the GitHub notifications, more noise than signal.

- _How will we know that the problem is resolved?_
Want to limit slack channel notifications to PR merges and include the branch that's being merged into

Haven't spent enough time with the slack integration to know if this can be done.

**Comment by brandocalrissian** [comment]
Related to #728

**Comment by brandocalrissian** [comment]
Changed the configuration on the GitHub side of the house to trigger slack notifications on PR events. This includes:

> Pull request opened, closed, reopened, edited, assigned, unassigned, review requested, review request removed, labeled, unlabeled, synchronized, ready for review, converted to draft, locked, or unlocked.

We can try this for a bit and see if it's an improvement.

**Comment by debjudy** [comment]
# of Github messages for the past 3 weeks

Week of 5/28 thru today: 22
Week of 5/22 to 5/28: 65
week of 5/15 to 5/21: 67
