### ISSUE TITLE
Spike: Research gaps in results returned

### ISSUE THREAD

**Issue by debjudy** [18F/cv_faq#784]
## Description
Not getting expected search results for search for "High Risk".  Not getting phrase "higher risk".  Purpose of spike is to identify other examples and then to assess if there is a pattern. 

## Tasks
- [ ] Search for additional unexpected or lack of expected result examples

**Comment by brandocalrissian** [comment]
Working on documenting this

**Comment by kimschulke** [comment]
No other examples have been identified as of yet. Search appears to be working for other word endings: (ing), (ed), (s)

**Comment by brandocalrissian** [comment]
Low and lower does the same thing. Maybe this should go to search.gov as an -er stem?

**Comment by brandocalrissian** [comment]
follow-up implementation will be in #840
