### ISSUE TITLE
SPIKE: Research SERP term highlighting

### ISSUE THREAD

**Issue by debjudy** [18F/cv_faq#806]
## Description
Site presently uses search.gov highlighting to highlight found terms on the results page.  The results page highlights words like "is", "what", etc. which are likely of minimal value to the user.  Is there a better way to highlight terms in results?  Is this something to bring to the attention of search.gov?

## Notes
Specific examples

- Search "what is spread" which shows highlighted terms of "what", "is" and "spread".  "spread" is only term that is useful to the user. 

- Search for “face masks” highlights “face” and “mask” separately but not together "facemask". "facemask" is the word we use on the site. 

- Search for “opening up america” highlights general words such as "open" and "up" are highlighted

~- Search for “high risk” does not retrieve all content with “higher risk,” such as “are people with disabilities at higher risk?”~ addressed with issue #840

**Comment by brandocalrissian** [comment]
Search results coming from search dot gov. Local search results doing a word-based highlight (different). If there were complete words with spaces on both sides are in results, those are highlighted. Would include "is" if "is" is a search term.

**Comment by brandocalrissian** [comment]
Please add examples here

**Comment by brandocalrissian** [comment]
Deb to check and see if this is still relevant. If so, will update to make sure this covers what is relevant.

**Comment by debjudy** [comment]
Updated to focus on the highlighting of terms and not the results returned.

**Comment by brandocalrissian** [comment]
Blocked pending search research/decision

**Comment by debjudy** [comment]
9/16 update from Dawn: Still in progress and further along but no target date yet.

**Comment by brandocalrissian** [comment]
Project wrapped up. No longer needed.
