### ISSUE TITLE
SPIKE: Research best approach to ensure category pages are not cached in SERPs

### ISSUE THREAD

**Issue by brandocalrissian** [18F/cv_faq#841]
As a content administrator I want to ensure that outdated or deleted category pages are not cached with potentially incorrect or outdated content.

**Comment by jonadecker** [comment]
In digging into best practices, using metas is no longer the recommended method of setting expire or no-cache info for pages. The preferred method is to use the HTTP headers. It's not clear to me if this is possible in the Jekyll/Federalist environment and using metas might be an easier lift. Thoughts @danielnaab ? 

Some resources:
- https://simonhearne.com/2019/http-headers-fast-and-secure/#caching
- https://www.mnot.net/cache_docs/
- https://web.dev/http-cache/#cache-control
- https://web.dev/http-cache/#validating-cached-responses-with-etags

**Comment by danielnaab** [comment]
@jonadecker Do we have an example of where the content is cached too long? If the issue is with Google SERPs, I'm not sure that cache settings is what we want to change.

**Comment by brandocalrissian** [comment]
Nothing much to do here. If the crawlers are slow to index the site... They're pinging the site map daily but ignoring it.
