### ISSUE TITLE
Use HTTPS URLs when available

### ISSUE THREAD

**Issue by danielnaab** [18F/cv_faq#855]
## Description

As site visitor, I would like my browsing privacy respected with secure links to external content.

## Notes

We are inconsistent with usage of https vs http URLs - this ticket is to go over them and replace.

## Acceptance Criteria
- [x] http URLs replaced with https, when available

## Definition of Done
- [ ] ~~Approved and merged from content administrator~~
- [x] Merged to production by engineer
- [ ] ~~Notified agency content lead that content is published~~

**Comment by jonadecker** [comment]
Would it make sense to use protocol-agnostic links (//) or are these just mistyped rather than copy-pasted URLs?

**Comment by danielnaab** [comment]
> Would it make sense to use protocol-agnostic links (//) or are these just mistyped rather than copy-pasted URLs?

Nowadays I think it's considered best-practice to always link explicitly to https - and yes I suspect they're just mistyped by the content provider. HTMLProofer has an `enforce_https` option we can enable to catch this earlier...
