### ISSUE TITLE
Count of search results returned is inaccurate.

### ISSUE THREAD

**Issue by debjudy** [18F/cv_faq#875]
Information shared with search.gov on 6/30.  Awaiting feedback.  

On faq.coronavirus.gov with the i14y endpoint, we're getting results counts back from the first page of search results (offset=0) that doesn't match the number of results returned.

For example, this URL (with the access key removed):

https://search.usa.gov/api/v2/search/i14y?affiliate=faq.coronavirus.gov&access_key=XXXX&query=covid&limit=26&enable_highlighting=true

... returns an array of 23 results, but the returned counts are
total: 273, next_offset: 26.

**Comment by debjudy** [comment]
Search.gov Tier 2 Support (TTS Solutions Support)
Jul 6, 2020, 8:49 PM EDT

Hi Daniel,

Apologies for the delay, but our team has replicated the issue and is now looking into it. Unfortunately, we're on a big backlog of work, so this might take a while for us to address. Is it impacting other search functionalities? If so, please let us know.

Apologies - and thank you so much for reporting.

Best,
Ayush
Tier 2 Support

**Comment by brandocalrissian** [comment]
Deb reaching out to Dawn again next week, this might not live too much longer.

**Comment by debjudy** [comment]
Provided multiple examples where counts are off on July 14. 

- Search for "anxiety" returns 3 results but states that there are 6. https://faq.coronavirus.gov/search/?query=anxiety
- Search for "SNAP" returns 3 results but states that there are 4. https://faq.coronavirus.gov/search/?query=snap
- Search for "July 15" returns 4 results but states that there are 5. https://faq.coronavirus.gov/search/?query=july+15
- Search for 'Tax Day" returns 19 results but states that there are 21. https://faq.coronavirus.gov/search/?query=tax+day

**Comment by brandocalrissian** [comment]
Don't do anything on this until a proposal for changing search is denied. Only relevant if staying on search.gov.

**Comment by debjudy** [comment]
Update from Dawn @ search.gov: Item still in queue no targeted completion date provided.

**Comment by debjudy** [comment]
9/16 update from Dawn: Still in progress and further along but no target date yet.

**Comment by debjudy** [comment]
10/2 Heard from search.gov and they are working on this.

**Comment by danielnaab** [comment]
12/22 Heard from search.gov, and they will not be fixing this bug at this time.

> Search.gov Tier 2 Support (TTS Solutions Support)
> 
> Dec 22, 2020, 11:58 AM EST
> 
> Hi Daniel,
> 
> Hope all is well. I just wanted to update you on this ticket - we've taken this to the team and noted that it's an issue, but unfortunately with our limited resources and the critical issues on our plate, we haven't been able to address this for the time being, and likely won't be able to for a while.
> 
> Please do reach out again with any additional questions - we're happy to help where we can. Closing this ticket for now.
> 
> Thanks and happy holidays,
> Ayush
> Search.gov Tier 2 Support

**Comment by brandocalrissian** [comment]
Project wrapped up. No longer needed.
