### ISSUE TITLE
Experiment with terms in type ahead

### ISSUE THREAD

**Issue by debjudy** [18F/cv_faq#881]
## Description
Shift the responses in type ahead to suggest terms instead of specific questions. 

- _What problem does this issue address for the public?_
Incongruity between results in type ahead and SERP.  (Example is searching for "Kid")

## Notes
[Additional context, known dependencies, blockers, links to design documents, etc]

## Acceptance Criteria
- [ ]

## Tasks
- [ ] PO approved
- [ ] Usability tested

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Code is properly styled per USWDS
- [ ] Finished design has been compared against mockup
- [ ] Documentation is complete
- [ ] CircleCI tests have passed
- [ ] Automated accessibility scans have passed
- [ ] Manual accessibility testing completed
- [ ] Code has been successfully built and deployed into a staging (dev) environment

**Comment by brandocalrissian** [comment]
Needs 👍 from the team to close this
