### ISSUE TITLE
Agree on sphere of influence principles

### ISSUE THREAD

**Issue by brandocalrissian** [18F/cv_faq#924]
what we can change, influence, and have to live with.

**Comment by brandocalrissian** [comment]
Everyone, please review the [sphere of influence document](https://docs.google.com/presentation/d/1ax6WIyAGAZK8QIrb_j94IAwGIldFSzOD8OJWC_4cEM4/edit?ts=5f29b782#slide=id.p).

**Comment by kimschulke** [comment]
Reviewed and agreed on documentation.
