### ISSUE TITLE
Rename production branch per digital gov guidance

### ISSUE THREAD

**Issue by brandocalrissian** [18F/cv_faq#927]
Now would be a good time to do it

**Comment by brandocalrissian** [comment]
New _main_ branch pushed to gh by Dan. Configured as the production branch in Federalist. Branch is protected to limit the users who can push to it.

Will keep the old branch around as a safety net for a little while, but it's locked down enough to prevent repo admins from accidentally pushing to it.

**Comment by brandocalrissian** [comment]
Can't close this ticket until we verify the production push goes as planned.

**Comment by brandocalrissian** [comment]
Production pushed worked yesterday.

**Comment by brandocalrissian** [comment]
Can't delete _master_ because [a pull request](https://github.com/18F/cv_faq/pull/911) depends on it.

**Comment by brandocalrissian** [comment]
When this is resolved, I can remove the branch restrictions so we can delete _master_.

**Comment by danielnaab** [comment]
> When this is resolved, I can remove the branch restrictions so we can delete _master_.

The PR has been updated to refer to the preview branch.

**Comment by brandocalrissian** [comment]
Done. Branch deleted.
