### ISSUE TITLE
SPIKE: improve search capabilities

### ISSUE THREAD

**Issue by brandocalrissian** [18F/cv_faq#928]
Evaluate if there is another option which we could use for search.

**Comment by danielnaab** [comment]
See #860 for a summary of various problems with the existing search, of which most still apply.

Below are different options we could take, and a summary of level-of-effort.

## Status quo

Keep open making additional small tweaks to existing system.

Known improvements we can make:

- Manually remove "| Coronavirus FAQ" from search.gov search results

## Client-side search

The original FAQ dev team implemented Fuse.js client-side search for the initial search suggestions drop-down, which was subsequently removed in favor of the curated search term list.

From prior testing, we found that this client-side search provides good results. Similar to search.gov, there are gaps that "best bests" and "routed query" features provide benefit.

A secondary benefit of doing client-side search is that we can format the search results list in a more FAQ-context aware manner.

Implementing client-side search is a one to two day development effort. Routed query and best bets could either continue to be managed via search.gov, or be reimplemented client-side.

Client-side reimplementation of routed queries and best bets would involve a requirements gathering process and ultimately would require adding additional fields to questions and categories. This would take one week of development time and team participation.

Search metrics could continue to be collected via search.gov, if we continue to use it for best bets and routed queries. However, if we reimplement client-side, we would need to start posting the search analytics to DAP. This would involve development effort (conservatively, two days) and process changes for how we report search metrics (level-of-effort uncertain to me @debjudy).

Risks with this approach are that there are unknowns surrounding search quality and process that would likely increase the level-of-effort and delay going to production.

**Comment by debjudy** [comment]
@danielnaab Search data is already populating to DAP, so no additional work required there.

**Comment by brandocalrissian** [comment]
There's a doc with the findings. If we act on it or not is a separate decision.
